version: '3.8'

services:
  tibia-bot:
    build:
      context: .
    container_name: tibia-bot-app
    environment:
      TOKEN: ${TOKEN}
      DATABASE_URL: ${DATABASE_URL}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs