akka.http {
  host-connection-pool {
    max-connections = 16
    max-open-requests = 4096
    response-entity-subscription-timeout = 10.seconds

    per-host-override = [
      {
        host-pattern = "api.tibiadata.com"
        max-connections = 64
      }
    ]
  }
}
