package com.tibiabot.domain

/** Maps the shorthand / alternative boss names players type in the `/boosted add`
 *  modal to the canonical boss name the boosted filters and API use. A pure lookup,
 *  built once (it was previously rebuilt inline on every modal submission). */
object BossAliases {

  private val aliases: Map[String, String] = Map(
    "oberon" -> "grand master oberon",
    "scarlett" -> "scarlett etzel",
    "scarlet" -> "scarlett etzel",
    "timira" -> "timira the many-headed",
    "timira the many headed" -> "timira the many-headed",
    "timira many headed" -> "timira the many-headed",
    "timira many-headed" -> "timira the many-headed",
    "magma" -> "magma bubble",
    "rotten final" -> "bakragore",
    "yselda" -> "megasylvan yselda",
    "zelos" -> "king zelos",
    "despor" -> "dragon pack",
    "dragon hoard" -> "dragon pack",
    "vengar" -> "dragon pack",
    "maliz" -> "dragon pack",
    "bruton" -> "dragon pack",
    "greedok" -> "dragon pack",
    "vilear" -> "dragon pack",
    "crultor" -> "dragon pack",
    "dragon boss" -> "dragon pack",
    "dragon bosses" -> "dragon pack",
    "thorn knight" -> "the enraged thorn knight",
    "the thorn knight" -> "the enraged thorn knight",
    "shielded thorn knight" -> "the enraged thorn knight",
    "the shielded thorn knight" -> "the enraged thorn knight",
    "mounted thorn knight" -> "the enraged thorn knight",
    "the mounted thorn knight" -> "the enraged thorn knight",
    "paleworm" -> "the paleworm",
    "unwelcome" -> "the unwelcome",
    "yirkas" -> "yirkas blue scales",
    "vok" -> "vok the feakish",
    "irgix" -> "irgix the flimsy",
    "unaz" -> "unaz the mean",
    "utua" -> "utua stone sting",
    "katex" -> "katex blood tongue",
    "voidborn" -> "the unarmored voidborn",
    "the voidborn" -> "the unarmored voidborn",
    "unarmored voidborn" -> "the unarmored voidborn",
    "urmahlullu" -> "urmahlullu the weakened",
    "winter bloom" -> "the winter bloom",
    "time guardian" -> "the time guardian",
    "souldespoiler" -> "the souldespoiler",
    "scourge of oblivion" -> "the scourge of oblivion",
    "lib final" -> "the scourge of oblivion",
    "lb final" -> "the scourge of oblivion",
    "sandking" -> "the sandking",
    "nightmare beast" -> "the nightmare beast",
    "moonlight aster" -> "the moonlight aster",
    "monster" -> "the monster",
    "ingol boss" -> "the monster",
    "ingol final" -> "the monster",
    "mega magmaoid" -> "the mega magmaoid",
    "lily of night" -> "the lily of night",
    "flaming orchid" -> "the flaming orchid",
    "fear feaster" -> "the fear feaster",
    "false god" -> "the false god",
    "enraged thorn knight" -> "the enraged thorn knight",
    "dread maiden" -> "the dread maiden",
    "diamond blossom" -> "the diamond blossom",
    "brainstealer" -> "the brainstealer",
    "blazing rose" -> "the blazing rose",
    "srezz" -> "srezz yellow eyes",
    "werelion serpent spawn" -> "srezz yellow eyes",
    "werelions serpent spawn" -> "srezz yellow eyes",
    "werelion goanna" -> "yirkas blue scales",
    "werelions goanna" -> "yirkas blue scales",
    "werelion scorpion" -> "utua stone sting",
    "werelions scorpion" -> "utua stone sting",
    "werelion hyena" -> "katex blood tongue",
    "werelions hyena" -> "katex blood tongue",
    "werelion hyaena" -> "katex blood tongue",
    "werelions hyaena" -> "katex blood tongue",
    "werelion werehyena" -> "katex blood tongue",
    "werelions werehyena" -> "katex blood tongue",
    "werelion werehyaena" -> "katex blood tongue",
    "werelions werehyaena" -> "katex blood tongue",
    "dragon king" -> "soul of dragonking zyrtarch",
    "zyrtarch" -> "soul of dragonking zyrtarch",
    "dragonking zyrtarch" -> "soul of dragonking zyrtarch",
    "dragon king zyrtarch" -> "soul of dragonking zyrtarch",
    "dragonking zyrtarch" -> "soul of dragonking zyrtarch",
    "dragonking" -> "soul of dragonking zyrtarch",
    "tenebris" -> "lady tenebris",
    "ratmiral" -> "ratmiral blackwhiskers",
    "plague seal" -> "plagirath",
    "pumin seal" -> "tarbaz",
    "jugg seal" -> "razzagorn",
    "vexclaw seal" -> "shulgrax",
    "undead seal" -> "ragiaz"
  )

  /** The canonical boss name for `name` (an already-lowercased player input), or
   *  `name` unchanged when it is not a known alias. */
  def canonical(name: String): String = aliases.getOrElse(name, name)
}
